@url = https://v9crg7vjyh.execute-api.eu-west-1.amazonaws.com/dev
@pk = < pk of the item >

###
GET {{url}}/post

### 
POST {{url}}/post
Accept: application/json
Content-Type: application/json

{
    "title": "Post title 2",
    "content": "Post content",
    "tag": "tag1, tag2",
    "author": ["author1", "author2"]
}
### 

GET {{url}}/post/{{pk}}
Accept: application/json

###

POST {{url}}/post/{{pk}}
Accept: application/json
Content-Type: application/json

{
    "title": "Post title",
    "content": "Post content updated",
    "tag": "tag1",
    "author": ["author1", "author3"]
}

### 
DELETE {{url}}/post/{{pk}}
