AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple database with CRUD layout

Parameters:
  region:
    Type: String
    Description: region in which the lambda functions operate
  apiStage:
    Type: String
    Description: stage used to deploy the API

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: gateway
      StageName: !Ref apiStage
      Models:
        Article:
          type: object
          required:
            - id
            - title
          properties:
            id:
              type: integer
            title:
              type: string
            tag: 
              type: string

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-function
      CodeUri: ./dist/create
      Handler: app.handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /post
            Method: post
            RestApiId: !Ref ApiGateway

  ReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: read-function
      CodeUri: ./dist/read
      Handler: app.handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /post/{id}
            Method: get
            RestApiId: !Ref ApiGateway

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-function
      CodeUri: ./dist/update
      Handler: app.handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /post/{id}
            Method: post
            RestApiId: !Ref ApiGateway

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-function
      CodeUri: ./dist/delete
      Handler: app.handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /post/{id}/delete
            Method: post
            RestApiId: !Ref ApiGateway

Outputs:
  ApiGateway:
    Description: "API Gateway endpoint URL for ${apiStage} stage for MyFunction"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiStage}/"

