@startuml REST-CRUD
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified>

!include <awslib/General/Users>
!include <awslib/mobile/APIGateway>
!include <awslib/mobile/APIGatewayEndpoint>
!include <awslib/Compute/Lambda>
!include <awslib/Database/DynamoDB>
!include <awslib/ManagementGovernance/OpsWorksLayers>
!include <awslib/Storage/SimpleStorageServiceS3Standard>

left to right direction

Users(b_users, "Clients", "")
Users(f_users, "Clients", "")
package "Deployment on AWS" {
    APIGateway(api, "MyGateway", "")
    APIGatewayEndpoint(e_create, "[POST] /article", "")
    APIGatewayEndpoint(e_read, "[GET] /article/{id}", "")
    APIGatewayEndpoint(e_update, "[POST] /article/{id}", "")
    APIGatewayEndpoint(e_delete, "[POST] /article/{id}/delete", "")
    Lambda(l_create, "Create article", "")
    Lambda(l_read, "Read article", "")
    Lambda(l_update, "Update article", "")
    Lambda(l_delete, "Delete article", "")
    DynamoDB(db, "Articles table", "")
    SimpleStorageServiceS3Standard(s3, "Simple form frontend", "")
}

b_users --> api : interact directly with the API endpoint
api --> e_create
api --> e_read
api --> e_update
api --> e_delete
e_create --> l_create
e_read --> l_read
e_update --> l_update
e_delete --> l_delete
l_create --> db
l_read --> db
l_update --> db
l_delete --> db

f_users --> s3 : interact with some form of basic frontend, for example a bucked serving a website
s3 -right-> api

@enduml