@startuml CTMobi counter bot
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified>

!include <awslib/General/Users>
!include <awslib/mobile/APIGateway>
!include <awslib/mobile/APIGatewayEndpoint>
!include <awslib/Compute/Lambda>
!include <awslib/SecurityIdentityAndCompliance/IAMRole>
!include <awslib/ManagementGovernance/OpsWorksLayers>

left to right direction

Users(users, "Clients", "")
package "Deployment on AWS" {
    APIGateway(api, "MyGateway", "")
    APIGatewayEndpoint(func, "/func", "")
    APIGatewayEndpoint(func2, "/func2", "")
    Lambda(lambda, "MyFunction", "")
    Lambda(lambda2, "MyFunction2", "")
    IAMRole(iam, "IAM role of MyFunction", "")
    IAMRole(iam2, "IAM role of MyFunction2", "")
    OpsWorksLayers(layer, "MyLayer", "")
}

users --> api : interact with the API endpoint
api --> func : the endpoint belogns to this gateway
api --> func2 : the endpoint belogns to this gateway
func --> lambda : invoke MyFunction
func2 --> lambda2 : invoke MyFunction2
lambda <--> layer
lambda2 <--> layer
iam -up-> lambda : IAM role is assigned to the lambda function
iam2 -up-> lambda2 : IAM role is assigned to the lambda function

@enduml